accounts/urls.py
"""Defines URL patterns for accounts."""

from django.urls import path, include

from . import views


app_name = 'accounts'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),
    # Registration page.
    path('register/', views.register, name='register'),
]

imageGeneration/urls.py
'''Defines URL patterns for imageGeneration.'''

from django.urls import path

from . import views

app_name = 'imageGeneration'

urlpatterns = [
    # Generated Images
    path('image/', views.image, name='image'),
    # Entire gallery
    path('gallery/', views.gallery, name='gallery'),
    # Prompt
    path('prompt/', views.prompt, name='prompt'),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all topics.
    path('generation/', views.generation, name='generation'),
    # Page that displays the generated images
    path('gallery/', views.gallery, name='gallery'),
    # Page that displays the user image generation history
    path('user_history/', views.user_history, name='user_history'),
    # Page to show the about us content
    path('about/', views.about, name='about'),
    
    # Page to display the current prompt instance text
    path('prompt/', views.prompt, name='prompt'),
    
    #Addition for button click execution of newPromptInstance
    path('run_prompt_script/', views.run_prompt_script, name='run_prompt_script'),
    
    #Addition for button click execution of newImageInstance
    path('run_image_script/', views.run_image_script, name='run_image_script'),
    
    #Addition for the page to create a request by user
    path('user_image/', views.user_image, name='user_image'),
    
]

ll_project/urls.py
from django.contrib import admin
from django.urls import path, include

# Imported to display image files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('imageGeneration/', include('imageGeneration.urls')),
    path('', include('learning_logs.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.conf import settings

from django.shortcuts import render
import subprocess
from django.http import HttpResponse
import os
from imageGeneration.models import Prompt, Image, UserImage


from django.shortcuts import render, get_object_or_404


def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

# Addition of imageForge Views

@login_required
def generation(request):
    """Show generation page."""
    return render(request, 'learning_logs/generation.html')

def gallery(request):
    """Show gallery page."""
    return render(request, 'learning_logs/gallery.html')

def user_history(request):
    """Show user history page."""
    return render(request, 'learning_logs/user_history.html')

def about(request):
    """Show the about page."""
    return render(request, 'learning_logs/about.html')

def prompt(request):
    most_recent_prompt = Prompt.objects.latest('date_added')
    context = {'prompt': most_recent_prompt}
    return render(request, 'learning_logs/prompt.html', context)


# Script execution on button click

def run_prompt_script(request):
    script_path = os.path.join(settings.BASE_DIR, 'newPromptInstance.py')
    subprocess.run(["python", script_path], cwd=settings.BASE_DIR)
    return redirect('learning_logs:prompt')

def run_image_script(request):
    script_path = os.path.join(settings.BASE_DIR, 'newImageInstance.py')
    subprocess.run(["python", script_path], cwd=settings.BASE_DIR)
    return render(request, 'learning_logs/user_image.html')



def user_image(request):
    image_instance_object = Image.objects.latest('datetime_field')
    image_instance_id = image_instance_object.id
    image = Image.objects.get(id=image_instance_id)
    user_image_instance = UserImage()
    user_image_instance.text_field = image.text_field
    user_image_instance.datetime_field = image.datetime_field
    user_image_instance.image_field = image.image_field
    user_image_instance.local_url = image.local_url
    user_image_instance.owner = request.user
    
    
    # print("image_instance_object:", image_instance_object)
    # print("image_instance_id:", image_instance_id)
    # print("image:", image)
    # print("user_image_instance:", user_image_instance)
    # print("user_image_instance.text_field:", user_image_instance.text_field)
    # print("user_image_instance.datetime_field:", user_image_instance.datetime_field)
    # print("user_image_instance.image_field:", user_image_instance.image_field)
    # print("user_image_instance.local_url:", user_image_instance.local_url)
    # print("user_image_instance.owner:", user_image_instance.owner)

    
    user_image_instance.save()
    
    print('User image instance has been created with an ID of', image_instance_id)
    
    # Pass the field values to the template or do further processing
    context = {
        'text_field': user_image_instance.text_field,
        'datetime_field': user_image_instance.datetime_field,
        'local_url': user_image_instance.local_url,
        'owner': user_image_instance.owner,
        'text_field': user_image_instance.text_field,
        'local_url': user_image_instance.image_field.url,
    }
    
    return render(request, 'learning_logs/user_image.html', context)

learning_logs/templates/learning_logs/about.html
{% extends 'learning_logs/base.html' %} {% load static %} {% block content %}
<style>
  body {
    background-image: url("{% static 'explosion2.png' %}");
    background-size: cover;
    background-position: 100% 40%; /* Adjusted vertical position */
    background-repeat: no-repeat;
    min-height: calc(
      100vh - 100px
    ); /* Adjust the height based on your navbar and footer heights */
    margin: 0;
    padding: 0;
  }

  .full-width {
    width: 100%;
  }

  .card-body {
    overflow: auto;
  }

  .text-container {
    max-height: 100%;
    overflow: auto;
  }
</style>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <div class="card mb-3" style="height: 30vh">
        <div class="card-body d-flex align-items-center justify-content-center">
          <div
            class="border border-secondary rounded p-3 text-center text-container"
            style="width: 100%"
          >
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
              Vivamus scelerisque est in velit sagittis, vel dignissim turpis
              varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
              tempus metus, in varius turpis magna at velit. Aenean semper
              semper felis, et consectetur risus ullamcorper sed. Donec id neque
              urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
              efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
              neque sed urna.
            </p>
            <br />
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
              Vivamus scelerisque est in velit sagittis, vel dignissim turpis
              varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
              tempus metus, in varius turpis magna at velit. Aenean semper
              semper felis, et consectetur risus ullamcorper sed. Donec id neque
              urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
              efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
              neque sed urna.
            </p>
          </div>
        </div>
      </div>
      <div class="mt-4"></div>
      <!-- 20% gap between boxes -->
      <div class="card" style="height: 30vh">
        <div class="card-body d-flex align-items-center justify-content-center">
          <div
            class="border border-secondary rounded p-3 text-center text-container"
            style="width: 100%"
          >
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
              Vivamus scelerisque est in velit sagittis, vel dignissim turpis
              varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
              tempus metus, in varius turpis magna at velit. Aenean semper
              semper felis, et consectetur risus ullamcorper sed. Donec id neque
              urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
              efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
              neque sed urna.
            </p>
            <br />
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Suspendisse rhoncus dapibus arcu, non tempus ligula aliquet eu.
              Vivamus scelerisque est in velit sagittis, vel dignissim turpis
              varius. Nullam ultrices, nunc nec mattis accumsan, ipsum nibh
              tempus metus, in varius turpis magna at velit. Aenean semper
              semper felis, et consectetur risus ullamcorper sed. Donec id neque
              urna. Cras a diam a mi auctor venenatis. Fusce tincidunt, mi in
              efficitur rhoncus, nisi risus auctor nisi, sit amet faucibus ipsum
              neque sed urna.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>imageForge</title>

    {% load django_bootstrap5 %} {% bootstrap_css %} {% bootstrap_javascript %}
    {% load static %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
          imageForge</a
        >

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarCollapse"
          aria-controls="navbarCollapse"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul
            class="navbar-nav me-auto mb-2 mb-md-0 navbar-nav d-flex justify-content-evenly w-100"
          >
            <li class="nav-item">
              <a class="nav-link" href="{% url 'imageGeneration:gallery' %}">
                Gallery</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:generation' %}">
                Generation</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'imageGeneration:image' %}">
                User History</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{% url 'learning_logs:about' %}">
                About</a
              >
            </li>
          </ul>
          <!-- End of links on left side of navbar -->

          <!-- Account-related links -->
          <ul class="navbar-nav ms-auto mb-2 mb-md-0">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <span class="navbar-text me-2">Hello, {{ user.username }}. </span>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">
                Register</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}"> Log in</a>
            </li>
            {% endif %}
          </ul>
          <!-- End of account-related links -->

          {% if user.is_authenticated %}
          <form action="{% url 'accounts:logout' %}" method="post">
            {% csrf_token %}
            <button name="submit" class="btn btn-outline-secondary btn-sm">
              Log out
            </button>
          </form>
          {% endif %}
        </div>
        <!-- Closes collapsible parts of navbar -->
      </div>
      <!-- Closes navbar's container -->
    </nav>
    <!-- End of navbar -->

    <main class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>

      <div>{% block content %}{% endblock content %}</div>
    </main>
    <footer class="bg-dark text-white py-3 fixed-bottom">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <div class="d-flex justify-content-start">
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-github-square social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-linkedin social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-twitter-square social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
              <a href="#" class="btn btn-outline-light me-2">
                <i
                  class="fab fa-instagram social-icon fa-2x"
                  aria-hidden="true"
                ></i>
              </a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="d-flex justify-content-end">
              <a href="#" class="btn btn-primary subscribe-btn">Subscribe</a>
            </div>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

  <p>Edit entry:</p>

  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_div }}
    <button name="submit">Save changes</button>
  </form>

{% endblock content %}

learning_logs/templates/learning_logs/generation.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Generation</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html>
  <head>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
    />
    <style>
      .button-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 50vh; /* Adjust the height to make buttons 15% higher */
      }
      .button-container .btn-generate-image {
        background-color: #28a745;
      }
    </style>
  </head>
  <body>
    {% csrf_token %}
    <div class="container">
      <div
        class="row justify-content-center align-items-center"
        style="min-height: 100vh"
      >
        <div class="col-md-6">
          <div class="text-center" style="margin-top: -40%">
            <button
              id="run-script-btn"
              type="submit"
              class="btn btn-success btn-lg"
            >
              GENERATE
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Include the jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- JavaScript code to handle the button click event -->
    <script>
      $(document).ready(function () {
        // Handle button click event
        $("#run-script-btn").click(function () {
          $.ajax({
            url: "/run_prompt_script/",
            type: "GET",
            success: function (data) {
              // Process the response data here
              console.log(data);
              window.location.href = "/prompt/"; // Redirect to /prompt on success
            },
            error: function (xhr, errmsg, err) {
              console.log(xhr.status + ": " + xhr.responseText);
              window.location.href = "/prompt/"; // Redirect to /prompt on error
            },
          });
        });
      });
    </script>
  </body>
</html>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %} {% load static %} {% block content %}
<style>
  body {
    background-image: url("{% static 'explosion2.png' %}");
    background-size: cover;
    background-position: center;
    min-height: calc(100vh + 350px);
    margin: 0;
    padding: 0;
  }

  .custom-div {
    height: 30vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
  }

  .custom-div h1 {
    font-size: calc(3vw + 1rem);
    max-width: 90%;
  }

  .custom-div p {
    font-size: calc(1vw + 0.5rem);
    max-width: 90%;
  }

  .custom-div .d-grid {
    width: 100%;
  }

  .custom-div .d-grid .btn {
    width: 100%;
  }

  @media (max-width: 767px) {
    /* Adjust the styles for smaller screens */
    .custom-div h1 {
      font-size: 2rem;
    }

    .custom-div p {
      font-size: 1rem;
    }
  }
</style>

<div class="p-3 mb-4 bg-light border rounded-3 custom-div" id="myDiv">
  <div class="container-fluid py-4">
    <h1 class="display-3">Welcome to imageForge!</h1>
    <p>Create randomly generated images with OpenAI's Dall•E 2 Model</p>
    <div class="d-grid gap-2 col-6 mx-auto">
      <a
        href="{% url 'imageGeneration:gallery' %}"
        class="btn btn-primary"
        type="button"
        >Visit Gallery</a
      >
      <a
        href="{% url 'learning_logs:generation' %}"
        class="btn btn-success"
        type="button"
        >Generation</a
      >
    </div>
  </div>
</div>
{% endblock content %}

learning_logs/templates/learning_logs/prompt.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>Prompt</h1>
{% endblock page_header %} {% block content %}

<!DOCTYPE html>
<html>
  <head>
    <title>Centered Div with Bootstrap</title>
    <!-- Include Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css"
    />
  </head>
  <body>
    <div
      class="container d-flex justify-content-center align-items-center"
      style="height: 100vh"
    >
      <div class="text-center" style="width: 30%">
        <form>
          <div class="mb-3">
            <label for="displayField" class="form-label"
              >Randomized Prompt</label
            >
            <p>{{ prompt.get_text }}</p>
          </div>
          <div class="mb-3">
            <button type="button" id="run-script-btn" class="btn btn-primary">
              New Prompt
            </button>
            <button type="button" id="run-image-btn" class="btn btn-success">
              Create Image
            </button>
          </div>
        </form>
      </div>
    </div>

    <!-- Include Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <!-- Include the jQuery library -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- JavaScript code to handle the button click event -->
    <script>
      $(document).ready(function () {
        // Handle button click event
        $("#run-script-btn").click(function () {
          $.ajax({
            url: "/run_prompt_script/",
            type: "GET",
            success: function (data) {
              // Process the response data here
              console.log(data);
              window.location.href = "/prompt/"; // Redirect to /prompt on success
            },
            error: function (xhr, errmsg, err) {
              console.log(xhr.status + ": " + xhr.responseText);
              window.location.href = "/prompt/"; // Redirect to /prompt on error
            },
          });
        });

        // Handle button click event
        $("#run-image-btn").click(function () {
          // Disable the 'Create Image' button
          $(this).prop("disabled", true);
          // Disable the 'New Prompt' button
          $("#run-script-btn").prop("disabled", true);

          $.ajax({
            url: "/run_image_script/",
            type: "GET",
            success: function (data) {
              // Process the response data here
              console.log(data);
              window.location.href = "/user_image/";
            },
            error: function (xhr, errmsg, err) {
              console.log(xhr.status + ": " + xhr.responseText);
            },
          });
        });
      });
    </script>
  </body>
</html>

{% endblock content %} learning_logs/templates/learning_logs/user_image.html

learning_logs/templates/learning_logs/user_history.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>User History</h1>
{% endblock page_header %} {% block content %} {% load static %}
<head>
  <title>Page Title</title>
  <!-- Add Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
  <style>
    .left-div {
      width: 300px;
      height: 300px;
      background-color: #f1f1f1;
      float: left;
    }

    .right-div {
      height: 300px;
      background-color: #f1f1f1;
      margin-left: 300px; /* width of the left div */
    }
  </style>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4 left-div"></div>
      <div class="col-md-8 right-div"></div>
    </div>
  </div>

  <!-- Add Bootstrap JS (if needed) -->
  <script src="{% static 'bootstrap.min.js' %}"></script>
</body>
{% endblock content %}

learning_logs/templates/learning_logs/user_image.html
{% extends 'learning_logs/base.html' %} {% block page_header %}
<h1>User Image</h1>
{% endblock page_header %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      .centered-div {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 80vh;
      }
    </style>
  </head>
  <body>
    <div class="centered-div">
      {% if local_url %}
      <img src="{{ local_url }}" alt="User Image" />
      <!-- Update this line -->
      {% else %}
      <p>No image available.</p>
      {% endif %}
      <br />
      <br />
      <br />
      <p>Prompt: {{ text_field }}</p>
      <!-- Remove this line -->
      <br />
      <br />
      <a href="{% url 'imageGeneration:gallery' %}" class="btn btn-success"
        >Continue to Gallery</a
      >
    </div>
  </body>
</html>
{% endblock content %}